export const l10n = {
    "mediaFrameDefaultTitle":"Media",
    "url":"URL",
    "addMedia":"Add media",
    "search":"Search",
    "select":"Select",
    "cancel":"Cancel",
    "update":"Update",
    "replace":"Replace",
    "remove":"Remove",
    "back":"Back",
    "selected":"%d selected",
    "dragInfo":"Drag and drop to reorder media files.",
    "uploadFilesTitle":"Upload files",
    "uploadImagesTitle":"Upload images",
    "mediaLibraryTitle":"Media Library",
    "insertMediaTitle":"Add media",
    "createNewGallery":"Create a new gallery",
    "createNewPlaylist":"Create a new playlist",
    "createNewVideoPlaylist":"Create a new video playlist",
    "returnToLibrary":"\u2190 Go to library",
    "allMediaItems":"All media items",
    "allDates":"All dates",
    "noItemsFound":"No items found.",
    "insertIntoPost":"Insert into post",
    "unattached":"Unattached",
    "mine":"Mine",
    "trash":"Trash",
    "uploadedToThisPost":"Uploaded to this post",
    "warnDelete":"You are about to permanently delete this item from your site.\nThis action cannot be undone.\n 'Cancel' to stop, 'OK' to delete.",
    "warnBulkDelete":"You are about to permanently delete these items from your site.\nThis action cannot be undone.\n 'Cancel' to stop, 'OK' to delete.",
    "warnBulkTrash":"You are about to trash these items.\n  'Cancel' to stop, 'OK' to delete.",
    "bulkSelect":"Bulk select",
    "trashSelected":"Move to Trash",
    "restoreSelected":"Restore from Trash",
    "deletePermanently":"Delete permanently",
    "errorDeleting":"Error in deleting the attachment.",
    "apply":"Apply",
    "filterByDate":"Filter by date",
    "filterByType":"Filter by type",
    "searchLabel":"Search",
    "searchMediaLabel":"Search media",
    "searchMediaPlaceholder":"Search media items...",
    "mediaFound":"Number of media items found: %d",
    "noMedia":"No media items found.",
    "noMediaTryNewSearch":"No media items found. Try a different search.",
    "attachmentDetails":"Attachment details",
    "insertFromUrlTitle":"Insert from URL",
    "setFeaturedImageTitle":"Featured image",
    "setFeaturedImage":"Set featured image",
    "createGalleryTitle":"Create gallery",
    "editGalleryTitle":"Edit gallery",
    "cancelGalleryTitle":"\u2190 Cancel gallery",
    "insertGallery":"Insert gallery",
    "updateGallery":"Update gallery",
    "addToGallery":"Add to gallery",
    "addToGalleryTitle":"Add to gallery",
    "reverseOrder":"Reverse order",
    "imageDetailsTitle":"Image details",
    "imageReplaceTitle":"Replace image",
    "imageDetailsCancel":"Cancel edit",
    "editImage":"Edit image",
    "chooseImage":"Choose image",
    "selectAndCrop":"Select and crop",
    "skipCropping":"Skip cropping",
    "cropImage":"Crop image",
    "cropYourImage":"Crop your image",
    "cropping":"Cropping\u2026",
    "suggestedDimensions":"Suggested image dimensions: %1$s by %2$s pixels.",
    "cropError":"There has been an error cropping your image.",
    "audioDetailsTitle":"Audio details",
    "audioReplaceTitle":"Replace audio",
    "audioAddSourceTitle":"Add audio source",
    "audioDetailsCancel":"Cancel edit",
    "videoDetailsTitle":"Video details",
    "videoReplaceTitle":"Replace video",
    "videoAddSourceTitle":"Add video source",
    "videoDetailsCancel":"Cancel edit",
    "videoSelectPosterImageTitle":"Select poster image",
    "videoAddTrackTitle":"Add subtitles",
    "playlistDragInfo":"Drag and drop to reorder tracks.",
    "createPlaylistTitle":"Create audio playlist",
    "editPlaylistTitle":"Edit audio playlist",
    "cancelPlaylistTitle":"\u2190 Cancel audio playlist",
    "insertPlaylist":"Insert audio playlist",
    "updatePlaylist":"Update audio playlist",
    "addToPlaylist":"Add to audio playlist",
    "addToPlaylistTitle":"Add to Audio Playlist",
    "videoPlaylistDragInfo":"Drag and drop to reorder videos.",
    "createVideoPlaylistTitle":"Create video playlist",
    "editVideoPlaylistTitle":"Edit video playlist",
    "cancelVideoPlaylistTitle":"\u2190 Cancel video playlist",
    "insertVideoPlaylist":"Insert video playlist",
    "updateVideoPlaylist":"Update video playlist",
    "addToVideoPlaylist":"Add to video playlist",
    "addToVideoPlaylistTitle":"Add to video Playlist",
    "filterAttachments":"Filter media",
    "attachmentsList":"Media list",
    "settings":{
       "tabs":[
          
       ],
       "tabUrl":"https:\/\/wp.smokenetwork.nl\/wp-admin\/media-upload.php?chromeless=1",
       "mimeTypes":{
          "image":"Images",
          "audio":"Audio",
          "video":"Video",
          "application\/msword,application\/vnd.openxmlformats-officedocument.wordprocessingml.document,application\/vnd.ms-word.document.macroEnabled.12,application\/vnd.ms-word.template.macroEnabled.12,application\/vnd.oasis.opendocument.text,application\/vnd.apple.pages,application\/pdf,application\/vnd.ms-xpsdocument,application\/oxps,application\/rtf,application\/wordperfect,application\/octet-stream":"Documents",
          "application\/vnd.apple.numbers,application\/vnd.oasis.opendocument.spreadsheet,application\/vnd.ms-excel,application\/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application\/vnd.ms-excel.sheet.macroEnabled.12,application\/vnd.ms-excel.sheet.binary.macroEnabled.12":"Spreadsheets",
          "application\/x-gzip,application\/rar,application\/x-tar,application\/zip,application\/x-7z-compressed":"Archives"
       },
       "captions":true,
       "nonce":{
          "sendToEditor":"e31e0eb3c5",
          "setAttachmentThumbnail":"a92d91650d"
       },
       "post":{
          "id":129,
          "nonce":"f951d79df7",
          "featuredImageId":-1
       },
       "defaultProps":{
          "link":"none",
          "align":"",
          "size":""
       },
       "attachmentCounts":{
          "audio":1,
          "video":1
       },
       "oEmbedProxyUrl":"https:\/\/wp.smokenetwork.nl\/wp-json\/oembed\/1.0\/proxy",
       "embedExts":[
          "mp3",
          "ogg",
          "flac",
          "m4a",
          "wav",
          "mp4",
          "m4v",
          "webm",
          "ogv",
          "flv"
       ],
       "embedMimes":{
          "mp3":"audio\/mpeg",
          "ogg":"audio\/ogg",
          "flac":"audio\/flac",
          "m4a":"audio\/mpeg",
          "wav":"audio\/wav",
          "mp4":"video\/mp4",
          "m4v":"video\/mp4",
          "webm":"video\/webm",
          "ogv":"video\/ogg",
          "flv":"video\/x-flv"
       },
       "contentWidth":null,
       "months":[
          {
             "year":"2023",
             "month":"2",
             "text":"February 2023"
          }
       ],
       "mediaTrash":0,
       "infiniteScrolling":0
    }
 };